### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gaul** [RodrigoDavy/Kana-Drill-Plus#2]
Does master lack some resources?  I cannot compile:

```
$ ./gradlew assembleDebug

> Task :app:compileDebugJavaWithJavac
/home/gaul/work/Kana-Drill-Plus/app/src/main/java/com/jorgecastillo/kanadrill/HiraganaTrainingActivity.java:15: error: cannot find symbol
    sounds = new int[]{R.raw.a,R.raw.i,R.raw.u,R.raw.e,R.raw.o,
                        ^
  symbol:   variable raw
  location: class R
```

**Comment by RodrigoDavy** [comment]
It does lack resources. I wanted to find voice samples to show along with the hiraganas/katakanas, I was using samples that I found on an website, but I didn't have the license or permition to use it, so I couldn't upload them to git

**Comment by gaul** [comment]
Could we add silent placeholders for now?

**Comment by RodrigoDavy** [comment]
Sure thing!

**Comment by RodrigoDavy** [comment]
I just added the placeholder files

**Comment by gaul** [comment]
Tested locally; thank you!
