### ISSUE TITLE
R.raw.wo missing

### ISSUE THREAD

**Issue by gaul** [RodrigoDavy/Kana-Drill-Plus#8]
Four occurrences in sounds have duplicate references to `R.raw.o` and none to `R.raw.wo`.

**Comment by RodrigoDavy** [comment]
It seems that the pronunciation for the "o" and "wo" is the same (o), so I decided there was no point in making a separate wo sound file.

I don't know if that's the case for all of Japan, but that's what I found earlier when I looked for the pronunciation of the kanas. I'll need to check this later to confirm, but, please, let me know if I'm wrong here :P

**Comment by gaul** [comment]
Sorry I am still learning Japanese; you are correct:

https://japanese.stackexchange.com/questions/3667/how-do-you-pronounce-%E3%82%92-after-a-subject
